version: "3"
services:
  api:
    container_name: api-ts
    build: .
    ports:
      - 5000:3050
    depends_on:
      - db
  
  db:
    container_name: mongodb
    image: mongo:latest
    ports:     
      - 27017:27017
      - 28017:28017
