version: "3"
services:
  api:
    container_name: api-ts
    build: .
    ports:
      - 5000:3050
    volumes:
      - ./dist:/usr/src/app
      - ./node_modules:/node_modules
    depends_on:
      - db
  
  db:
    container_name: mongodb
    image: mongo:latest
    ports:     
      - 27017:27017
